



default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: rails_react_development
  username: postgres
  password: password

test:
  <<: *default
  database: rails_react_test
  username: postgres
  password: password

production:
  <<: *default
  database: rails_react_production
  username: postgres
  password: password